export type Response = {
  time: string,
  date: string,
  type: string,
  username: string,
  processId: string,
}

export type BotFormData = {
  username: string;
  device: string;
  password: string;
  "speed-multiplier": number;
  "truncate-sources": string,
  "blogger-followers"?: string[],
  "hashtag-likers-top"?: string[],
  "unfollow-non-followers"?: string,
  "unfollow-skip-limit"?: string,
  "working-hours"?: string[],
};

export type SessionConfig = {
  args: {
    config: string,
    unfollow: number | string,
    unfollow_non_followers: number | string,
    unfollow_any_non_followers: string,
    unfollow_any_followers: string,
    unfollow_any: number | string,
    min_following: number,
    sort_followers_newest_to_oldest: boolean,
    unfollow_delay: number,
    unfollow_skip_limit: number | string,
    app_id: string,
    cloned_app_mode: number | string,
    device: string,
    username: string,
    password: string,
    relog_after_block: boolean,
    relog_delay: string,
    likes_count: string,
    likes_percentage: string,
    total_likes_limit: string,
    total_follows_limit: string,
    total_unfollows_limit: string,
    total_watches_limit: string,
    total_successful_interactions_limit: string,
    total_interactions_limit: string,
    stories_count: string,
    stories_percentage: string,
    carousel_count: string,
    carousel_percentage: string,
    watch_video_time: string,
    watch_photo_time: string,
    interactions_count: string,
    interact_percentage: string,
    can_reinteract_after: string,
    can_recheck_after: string,
    repeat: string,
    follow_percentage: string,
    follow_limit: number,
    skipped_list_limit: string,
    fling_when_skipped: string,
    speed_multiplier: number | string,
    screen_sleep: boolean,
    debug: boolean,
    screen_record: boolean,
    close_apps: boolean,
    interact: string | string[],
    hashtag_likers: string | string[],
    delete_interacted_users: boolean,
    scrape_to_file: string | string[],
    total_scraped_limit: string,
    comment_percentage: string,
    total_comments_limit: string,
    pm_percentage: string,
    total_pm_limit: string,
    max_comments_pro_user: string,
    end_if_likes_limit_reached: boolean,
    end_if_follows_limit_reached: boolean,
    end_if_watches_limit_reached: boolean,
    end_if_comments_limit_reached: boolean,
    end_if_pm_limit_reached: boolean,
    truncate_sources: string,
    shuffle_jobs: boolean,
    working_hours: string[]
    time_delta: string,
    disable_filters: boolean,
    total_crashes_limit: string | number,
    change_source_if_crash: boolean,
    timeout_startup: string,
    count_app_crashes: boolean,
    skipped_posts_limit: string | number
    uia_version: number,
    total_sessions: string | number,
    disable_block_detection: boolean,
    pre_script: string | string[],
    post_script: string | string[],
    move_folders_in_accounts: boolean,
    dont_type: boolean,
    mute_posts_after_follow: boolean,
    mute_stories_after_follow: boolean,
    analytics: boolean,
    blogger: string | string[],
    interact_from_file: string | string[],
    unfollow_from_file: string | string[],
    blogger_followers: string[],
    blogger_following: string | string[],
    blogger_post_likers: string | string[],
    blogger_post_limits: 0,
    feed: string,
    hashtag_likers_top: string[],
    hashtag_likers_recent: string | string[],
    hashtag_posts_recent: string | string[],
    hashtag_posts_top: string | string[],
    place_likers_top: string | string[],
    place_likers_recent: string | string[],
    place_posts_recent: string | string[],
    place_posts_top: string | string[],
    posts_from_file: string[],
    remove_followers_from_file: string | string[],
    delete_removed_followers: boolean,
    rotate_ip: boolean,
    telegram_reports: boolean,
    welcoming: string,
    max_welcoming_skips: number,
    check_chat_before_welcoming: boolean,
    time_delta_session: number,
    current_likes_limit: number,
    current_follow_limit: number,
    current_unfollow_limit: number,
    current_comments_limit: number,
    current_pm_limit: number,
    current_watch_limit: number,
    current_success_limit: number,
    current_total_limit: number,
    current_scraped_limit: number,
    current_crashes_limit: number
  },
}

export type SessionProfile = {
  profile: {
    posts: number,
    followers: number,
    following: number
  }
}

export type Session = {
  id: string,
  total_interactions: number,
  successful_interactions: number,
  total_followed: number,
  total_likes: number,
  total_comments: number,
  total_pm: number,
  total_watched: number,
  total_unfollowed: number,
  total_scraped: {},
  start_time: string,
  finish_time: string,
} & SessionConfig & SessionProfile;

export type Sessions = {
  sessions: Session[]
}

export type GetSessionFromPython = {
  following_now: number,
  followers_now: number,
  username: string,
}